In [121]:
#!unzip p.zip
!ls
!pwd

drive  sample_data
/content

# The Series Data Structure

In [122]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [123]:
import pandas as pd
pd.Series?

In [124]:
animals = ['Tiger', 'Bear', 'Moose']
pd.Series(animals)

0    Tiger
1     Bear
2    Moose
dtype: object

In [125]:
numbers = [1, 2, 3]
pd.Series(numbers)

0    1
1    2
2    3
dtype: int64

In [126]:
animals = ['Tiger', 'Bear', None]
pd.Series(animals)

0    Tiger
1     Bear
2     None
dtype: object

In [127]:
numbers = [1, 2, None]
pd.Series(numbers)

0    1.0
1    2.0
2    NaN
dtype: float64

In [128]:
import numpy as np
np.nan == None

False

In [129]:
np.nan == np.nan

False

In [130]:
np.isnan(np.nan)

True

In [131]:
sports = {'Archery': 'Bhutan',
          'Golf': 'Scotland',
          'Sumo': 'Japan',
          'Taekwondo': 'South Korea'}
s = pd.Series(sports)
s

Archery           Bhutan
Golf            Scotland
Sumo               Japan
Taekwondo    South Korea
dtype: object

In [132]:
s.index

Index(['Archery', 'Golf', 'Sumo', 'Taekwondo'], dtype='object')

In [133]:
s = pd.Series(['Tiger', 'Bear', 'Moose'], index=['India', 'America', 'Canada'])
s

India      Tiger
America     Bear
Canada     Moose
dtype: object

In [134]:
sports = {'Archery': 'Bhutan',
          'Golf': 'Scotland',
          'Sumo': 'Japan',
          'Taekwondo': 'South Korea'}
s = pd.Series(sports, index=['Golf', 'Sumo', 'Hockey'])
s

Golf      Scotland
Sumo         Japan
Hockey         NaN
dtype: object

# Querying a Series

In [135]:
sports = {'Archery': 'Bhutan',
          'Golf': 'Scotland',
          'Sumo': 'Japan',
          'Taekwondo': 'South Korea'}
s = pd.Series(sports)
s

Archery           Bhutan
Golf            Scotland
Sumo               Japan
Taekwondo    South Korea
dtype: object

In [136]:
s.iloc[2] # integer

'Japan'

In [137]:
s.loc['Sumo']

'Japan'

In [138]:
s[2]

'Japan'

In [139]:
s['Golf']

'Scotland'

In [140]:
sports = {99: 'Bhutan',
          100: 'Scotland',
          101: 'Japan',
          102: 'South Korea'}
s = pd.Series(sports)

In [141]:
#s[0] #This won't call s.iloc[0] as one might expect, it generates an error instead

In [142]:
s = pd.Series([100.00, 120.00, 101.00, 3.00])
s

0    100.0
1    120.0
2    101.0
3      3.0
dtype: float64

In [143]:
total = 0
for item in s:
    total+=item
print(total)

324.0

In [144]:
import numpy as np

total = np.sum(s)
print(total)

324.0

In [145]:
#this creates a big series of random numbers
s = pd.Series(np.random.randint(0,1000,10000))
s.head(20)

0     479
1     452
2     914
3     599
4     188
5     475
6     210
7     871
8     712
9      23
10    198
11    470
12    487
13    385
14    985
15    566
16    121
17    571
18    300
19    621
dtype: int64

In [146]:
len(s)

10000

In [147]:
%%timeit -n 100
summary = 0
for item in s:
    summary+=item

100 loops, best of 5: 1.82 ms per loop

In [148]:
%%timeit -n 100
summary = np.sum(s)

100 loops, best of 5: 98.1 µs per loop

In [149]:
s+=2 #adds two to each item in s using broadcasting
s.head(3)

0    481
1    454
2    916
dtype: int64

In [150]:
%%timeit -n 10
s = pd.Series(np.random.randint(0,1000,10000))
for label, value in s.iteritems():
    s.loc[label]= value+2

10 loops, best of 5: 434 ms per loop

In [151]:
%%timeit -n 10
s = pd.Series(np.random.randint(0,1000,10000))
s+=2 # s = s + 2

10 loops, best of 5: 458 µs per loop

In [152]:
s = pd.Series([1, 2, 3])
s.loc['Animal'] = 'Bears'
s

0             1
1             2
2             3
Animal    Bears
dtype: object

In [153]:
original_sports = pd.Series({'Archery': 'Bhutan',
                             'Golf': 'Scotland',
                             'Sumo': 'Japan',
                             'Taekwondo': 'South Korea'})
cricket_loving_countries = pd.Series(['Australia',
                                      'Barbados',
                                      'Pakistan',
                                      'England'], 
                                   index=['Cricket',
                                          'Cricket',
                                          'Cricket',
                                          'Cricket'])
all_countries = original_sports.append(cricket_loving_countries)

In [154]:
original_sports

Archery           Bhutan
Golf            Scotland
Sumo               Japan
Taekwondo    South Korea
dtype: object

In [155]:
cricket_loving_countries

Cricket    Australia
Cricket     Barbados
Cricket     Pakistan
Cricket      England
dtype: object

In [156]:
all_countries

Archery           Bhutan
Golf            Scotland
Sumo               Japan
Taekwondo    South Korea
Cricket        Australia
Cricket         Barbados
Cricket         Pakistan
Cricket          England
dtype: object

In [157]:
all_countries.loc['Cricket']

Cricket    Australia
Cricket     Barbados
Cricket     Pakistan
Cricket      England
dtype: object

# The DataFrame Data Structure

In [158]:
import pandas as pd
purchase_1 = pd.Series({'Name': 'Chris',
                        'Item Purchased': 'Dog Food',
                        'Cost': 22.50})
purchase_2 = pd.Series({'Name': 'Kevyn',
                        'Item Purchased': 'Kitty Litter',
                        'Cost': 2.50})
purchase_3 = pd.Series({'Name': 'Vinod',
                        'Item Purchased': 'Bird Seed',
                        'Cost': 5.00})
df = pd.DataFrame([purchase_1, purchase_2, purchase_3], index=['Store 1', 'Store 1', 'Store 2'])
df.head()

          Name Item Purchased  Cost
Store 1  Chris       Dog Food  22.5
Store 1  Kevyn   Kitty Litter   2.5
Store 2  Vinod      Bird Seed   5.0

In [159]:
df.loc['Store 2']

Name                  Vinod
Item Purchased    Bird Seed
Cost                    5.0
Name: Store 2, dtype: object

In [160]:
type(df.loc['Store 2'])

pandas.core.series.Series

In [161]:
df.loc['Store 1']

          Name Item Purchased  Cost
Store 1  Chris       Dog Food  22.5
Store 1  Kevyn   Kitty Litter   2.5

In [162]:
df.loc['Store 1', 'Cost']

Store 1    22.5
Store 1     2.5
Name: Cost, dtype: float64

In [163]:
df.T

                 Store 1       Store 1    Store 2
Name               Chris         Kevyn      Vinod
Item Purchased  Dog Food  Kitty Litter  Bird Seed
Cost                22.5           2.5        5.0

In [164]:
df.T.loc['Cost']

Store 1    22.5
Store 1     2.5
Store 2     5.0
Name: Cost, dtype: object

In [165]:
df['Cost']

Store 1    22.5
Store 1     2.5
Store 2     5.0
Name: Cost, dtype: float64

In [166]:
df.loc['Store 1']['Cost']

Store 1    22.5
Store 1     2.5
Name: Cost, dtype: float64

In [167]:
df.loc[:,['Name', 'Cost']]

          Name  Cost
Store 1  Chris  22.5
Store 1  Kevyn   2.5
Store 2  Vinod   5.0

In [168]:
df.drop('Store 1')

          Name Item Purchased  Cost
Store 2  Vinod      Bird Seed   5.0

In [169]:
df

          Name Item Purchased  Cost
Store 1  Chris       Dog Food  22.5
Store 1  Kevyn   Kitty Litter   2.5
Store 2  Vinod      Bird Seed   5.0

In [170]:
copy_df = df.copy()
copy_df = copy_df.drop('Store 1')
copy_df

          Name Item Purchased  Cost
Store 2  Vinod      Bird Seed   5.0

In [171]:
copy_df.drop?

In [172]:
del copy_df['Name']
copy_df

        Item Purchased  Cost
Store 2      Bird Seed   5.0

In [173]:
df['Location'] = 1  # une seule valeur  N * valeur 
df['Location'] =  [1,2,3] # list avec N elements

# Dataframe Indexing and Loading

In [174]:
df.columns

Index(['Name', 'Item Purchased', 'Cost', 'Location'], dtype='object')

In [175]:
df["Name"]

Store 1    Chris
Store 1    Kevyn
Store 2    Vinod
Name: Name, dtype: object

In [176]:
costs = df['Cost']
costs

Store 1    22.5
Store 1     2.5
Store 2     5.0
Name: Cost, dtype: float64

In [177]:
costs = 0

In [178]:
df

          Name Item Purchased  Cost  Location
Store 1  Chris       Dog Food  22.5         1
Store 1  Kevyn   Kitty Litter   2.5         2
Store 2  Vinod      Bird Seed   5.0         3

In [179]:
!cat pandas/olympics.csv

cat: pandas/olympics.csv: No such file or directory

In [180]:
df = pd.read_csv('pandas/olympics.csv')
df.head()

FileNotFoundError: ignored

In [ ]:
df = pd.read_csv('pandas/olympics.csv', index_col = 0, skiprows=1)
df.tail()

In [ ]:
df.columns

In [ ]:
for col in df.columns:
    if col[:2]=='01':
        df.rename(columns={col:'Gold' + col[4:]}, inplace=True)
    if col[:2]=='02':
        df.rename(columns={col:'Silver' + col[4:]}, inplace=True)
    if col[:2]=='03':
        df.rename(columns={col:'Bronze' + col[4:]}, inplace=True)
    if col[:1]=='№':
        df.rename(columns={col:'#' + col[1:]}, inplace=True) 

df.head()

# Querying a DataFrame

In [ ]:
df['Gold'] > 0

In [ ]:
only_gold = df.where(df['Gold'] > 0)
only_gold.head()

In [ ]:
only_gold['Gold'].count()

In [ ]:
df['Gold'].count()

In [ ]:
only_gold = only_gold.dropna()
only_gold.head()

In [ ]:
only_gold = df[df['Gold'] > 0]
only_gold.head()

In [ ]:
len(df[(df['Gold'] > 0) | (df['Gold.1'] > 0)])

In [ ]:
df[(df['Gold.1'] > 0) & (df['Gold'] == 0)]

# Indexing Dataframes

In [ ]:
df.head()

In [ ]:
df['country'] = df.index
df = df.set_index('Gold')
df.head()

In [ ]:
df = df.reset_index()
df.head()

In [ ]:
df = pd.read_csv('pandas/census.csv')
df.head()

In [ ]:
df['SUMLEV'].unique()

In [ ]:
df=df[df['SUMLEV'] == 50]
df.head()

In [ ]:
columns_to_keep = ['STNAME',
                   'CTYNAME',
                   'BIRTHS2010',
                   'BIRTHS2011',
                   'BIRTHS2012',
                   'BIRTHS2013',
                   'BIRTHS2014',
                   'BIRTHS2015',
                   'POPESTIMATE2010',
                   'POPESTIMATE2011',
                   'POPESTIMATE2012',
                   'POPESTIMATE2013',
                   'POPESTIMATE2014',
                   'POPESTIMATE2015']
df = df[columns_to_keep]
df.head()

In [ ]:
df = df.set_index(['STNAME', 'CTYNAME'])
df.head()

In [ ]:
df.loc['Michigan', 'Washtenaw County']

In [ ]:
df.loc[ [('Michigan', 'Washtenaw County'),
         ('Michigan', 'Wayne County')] ]

# Missing values

In [ ]:
df = pd.read_csv('pandas/log.csv')
df

In [ ]:
df.fillna?

In [ ]:
df = df.set_index('time')
df = df.sort_index()
df

In [ ]:
df.columns

In [ ]:
df = df.reset_index()
df = df.set_index(['time', 'user'])
df

In [ ]:
df = df.fillna(method='ffill')
df.head()